/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment;

//Part I imports
import weka.core.Instances; // For ARFF dataset
import weka.core.converters.ConverterUtils.DataSource; //For loading ARFF

//Part 2 imports
import weka.classifiers.Evaluation;
import weka.classifiers.functions.SimpleLinearRegression;
import weka.core.DenseInstance; // For creating new data instance
/**
 *
 * @author jabradzz
 */
public class FrmSalesPrediction_CalDol extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmSalesPrediction_CalDol.class.getName());

    /**
     * Creates new form FrmSalesPrediction_CalDol
     */
    public FrmSalesPrediction_CalDol() {
        this.setUndecorated(true);
        initComponents();
        java.awt.GraphicsEnvironment ge = java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment();
        java.awt.GraphicsDevice gd = ge.getDefaultScreenDevice();
        gd.setFullScreenWindow(this);
        loaddataset();
    }
    
    private void loaddataset()
    {
        try
        {
            Instances data = DataSource.read("dataset.arff");
            txtarff_surname.setText(data.toString());
            lblDatasetSize.setText("Dataset Size: " + data.numInstances());
            String output = "Month\tSales\n";
            for (int i = 0; i < data.numInstances(); i++)
            {
                double month = data.instance(i).value(0);
                double sales = data.instance(i).value(1);
                output += month + "\t" + sales + "\n";
            }
            txttabularview_surname.setText(output);
        }
        catch (Exception ex)
        {
            System.out.println(ex.getMessage());
        }
    }
    
    private String interpretError(double error, double meanActual) 
    {
        double relativeError = (error / meanActual) * 100;
        if (relativeError <= 10) return "Very Low Error";
        if (relativeError <= 20) return "Low Error";
        if (relativeError <= 30) return "Moderate Error";
        if (relativeError >= 50) return "High Error";
        else return "Very High Error";
    }
    
    private String interpretR2(double r2) 
    {
       if (r2 >= 0.90) return "Excellent";
       else if (r2 >= 0.70) return "Mahusay";
       else if (r2 >= 0.50) return "Katamtaman";
       else if (r2 >= 0.25) return "Mahina";
        else return "Skill Issue";
    }
    
    private String interpretCorrelation(double correlation) 
    {
        double absR = Math.abs(correlation);
        if (correlation >= 0.90) return "Excellent";
       else if (correlation >= 0.70) return "Very Good";
       else if (correlation >= 0.50) return "Moderate";
       else if (correlation >= 0.25) return "Weak";
        else return "Very Weak";
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblArff = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtarff_surname = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txttabularview_surname = new javax.swing.JTextArea();
        lblTabularView = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMonth_surname = new javax.swing.JTextField();
        btnAnalyze_surname = new javax.swing.JButton();
        lblPredictionValue_surname = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblResults = new javax.swing.JLabel();
        lblMAE = new javax.swing.JLabel();
        lblRMSE = new javax.swing.JLabel();
        lblR2 = new javax.swing.JLabel();
        lblCorrelation = new javax.swing.JLabel();
        lblDatasetSize = new javax.swing.JLabel();
        lblMAEDEF = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jLabel1.setFont(new java.awt.Font("Cantarell Extra Bold", 0, 18)); // NOI18N
        jLabel1.setText("Knowledge Analysis - Caligayahan | Dollentes");

        jLabel2.setFont(new java.awt.Font("Cantarell Extra Bold", 0, 18)); // NOI18N
        jLabel2.setText("Sales Prediction Using Simple Linear Regression");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        lblArff.setText("Attribute Relation File Format (ARFF)");

        txtarff_surname.setColumns(20);
        txtarff_surname.setRows(5);
        jScrollPane1.setViewportView(txtarff_surname);

        txttabularview_surname.setColumns(20);
        txttabularview_surname.setRows(5);
        jScrollPane2.setViewportView(txttabularview_surname);

        lblTabularView.setText("Tabular View");

        jLabel5.setText("Enter Month:");

        txtMonth_surname.addActionListener(this::txtMonth_surnameActionPerformed);

        btnAnalyze_surname.setText("Analyze");
        btnAnalyze_surname.addActionListener(this::btnAnalyze_surnameActionPerformed);

        lblPredictionValue_surname.setText("Prediction Value");

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));

        lblResults.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblResults.setText("Results");

        lblMAE.setBackground(new java.awt.Color(153, 255, 204));
        lblMAE.setText("MAE: ");
        lblMAE.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblMAE.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        lblMAE.setOpaque(true);

        lblRMSE.setBackground(new java.awt.Color(153, 255, 204));
        lblRMSE.setText("RMSE: ");
        lblRMSE.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblRMSE.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        lblRMSE.setOpaque(true);

        lblR2.setBackground(new java.awt.Color(153, 255, 204));
        lblR2.setText("R2: ");
        lblR2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblR2.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        lblR2.setOpaque(true);

        lblCorrelation.setBackground(new java.awt.Color(153, 255, 204));
        lblCorrelation.setText("Correlation Coefficient: ");
        lblCorrelation.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblCorrelation.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        lblCorrelation.setOpaque(true);

        lblDatasetSize.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDatasetSize.setText("Dataset Size:");

        lblMAEDEF.setText("MAE = Average kung gaano kalaki ang mali ng prediction");

        jLabel3.setText("RMSE = Sinusukat kung gaano kalaki ang error");

        jLabel4.setText("R2 = Gaano kaganda nage-explain ang model sa actual data");

        jLabel6.setText("Correlation Coefficient = Gaano kalakas ang relationship ng predicted at actual values");

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setText("➖");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setBackground(new java.awt.Color(204, 255, 204));
        jButton2.setText("◀");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMAE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblRMSE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblR2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCorrelation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMAEDEF)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))
                                .addGap(0, 93, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(lblResults, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(24, 24, 24))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(lblDatasetSize, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblResults, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMAE, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMAEDEF)
                .addGap(18, 18, 18)
                .addComponent(lblRMSE, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(32, 32, 32)
                .addComponent(lblR2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(lblCorrelation, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(46, 46, 46)
                .addComponent(lblDatasetSize, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblArff))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTabularView)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblPredictionValue_surname)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtMonth_surname, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAnalyze_surname))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblArff)
                            .addComponent(lblTabularView))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMonth_surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(btnAnalyze_surname))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPredictionValue_surname))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMonth_surnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMonth_surnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMonth_surnameActionPerformed

    private void btnAnalyze_surnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalyze_surnameActionPerformed
        // TODO add your handling code here:
        try 
        {
            Instances data = DataSource.read("dataset.arff");
            data.setClassIndex(1);
            SimpleLinearRegression model = new SimpleLinearRegression();
            model.buildClassifier(data);
            

            
            // reserve area for evaluation
            
            //evaluation
            Evaluation eval = new Evaluation(data);
            eval.evaluateModel(model, data);
            
            //Regression Metrics
            
            double mae = eval.meanAbsoluteError();
            double rmse = eval.rootMeanSquaredError();
            double correlation = eval.correlationCoefficient();
            double rSquared = correlation * correlation;
            
            double meanActual = data.attributeStats(data.classIndex()).numericStats.mean;
            
            String maeInterpretation = interpretError(mae, meanActual);
            String rmseInterpretation = interpretError(rmse, meanActual);
            String r2Interpretation = interpretR2(rSquared);
            String corrInterpretation = interpretCorrelation(correlation);
            
            lblMAE.setText("MAE: " + String.format("%.4f", mae) + " (" + maeInterpretation + ")");
            lblRMSE.setText("RMSE: " + String.format("%.4f", rmse) + " (" + rmseInterpretation + ")");
            lblR2.setText("R2: " + String.format("%.4f", rSquared) + " (" + r2Interpretation + ")");
            lblCorrelation.setText("Correlation Coefficient: " + String.format("%.4f", correlation) + " (" + corrInterpretation + ")");
            
            
            //Display evaluation metrics
            System.out.println("==== SIMPLE LINEAR REGRESSION EVALUATION ====");
            System.out.printf("MAE     : %.4f%n", mae);
            System.out.printf("RMSE    : %.4f%n", rmse);
            System.out.printf("R2      : %.4f%n", rSquared);
            System.out.printf("Correlation Coefficient     : %.4f%n", correlation);
            // evaluation
            
            double month = Double.parseDouble(txtMonth_surname.getText());
            
            DenseInstance test = new DenseInstance(data.numAttributes());
            test.setDataset(data);
            test.setValue(0, month);
            
            double prediction = model.classifyInstance(test);
            lblPredictionValue_surname.setText("Predicted Sales: " + String.format("%.2f", prediction));
        }
        catch (Exception e)
        {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnAnalyze_surnameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setState(java.awt.Frame.ICONIFIED);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         MainMenu previousWindow = new MainMenu();
          previousWindow.setVisible(true);
          previousWindow.setLocationRelativeTo(null);
    // 2. Close or hide the current window
          this.dispose(); 
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmSalesPrediction_CalDol().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalyze_surname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblArff;
    private javax.swing.JLabel lblCorrelation;
    private javax.swing.JLabel lblDatasetSize;
    private javax.swing.JLabel lblMAE;
    private javax.swing.JLabel lblMAEDEF;
    private javax.swing.JLabel lblPredictionValue_surname;
    private javax.swing.JLabel lblR2;
    private javax.swing.JLabel lblRMSE;
    private javax.swing.JLabel lblResults;
    private javax.swing.JLabel lblTabularView;
    private javax.swing.JTextField txtMonth_surname;
    private javax.swing.JTextArea txtarff_surname;
    private javax.swing.JTextArea txttabularview_surname;
    // End of variables declaration//GEN-END:variables
}
