/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment;

import weka.classifiers.Evaluation;
import weka.classifiers.functions.SimpleLinearRegression;
import weka.core.DenseInstance;
import weka.core.Instances;
import weka.core.converters.ConverterUtils;

/**
 *
 * @author Administrator
 */
public class SecondVersion extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SecondVersion.class.getName());

    /**
     * Creates new form SecondVersion
     */
    public SecondVersion() {
       this.setUndecorated(true);
        
        initComponents();
        
       
        java.awt.GraphicsEnvironment ge = java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment();
        java.awt.GraphicsDevice gd = ge.getDefaultScreenDevice();
        gd.setFullScreenWindow(this);
        
 
        java.awt.Dimension monitorSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        jPanel1.setPreferredSize(monitorSize);
        jPanel1.setSize(monitorSize);
        
      
        
 
        
        loaddataset();
    }
    
     private void loaddataset()
    {
        try
        {
            Instances data = ConverterUtils.DataSource.read("dataset.arff");
            arffView.setText(data.toString());
            lblDataSize.setText("Dataset Size: " + data.numInstances());
            String output = "Month\tSales\n";
            for (int i = 0; i < data.numInstances(); i++)
            {
                double month = data.instance(i).value(0);
                double sales = data.instance(i).value(1);
                output += month + "\t" + sales + "\n";
            }
            tblrView.setText(output);
        }
        catch (Exception ex)
        {
            System.out.println(ex.getMessage());
        }
    }
    
    private String interpretError(double error, double meanActual) 
    {
        double relativeError = (error / meanActual) * 100;
        if (relativeError <= 10) return "Very Low Error";
        if (relativeError <= 20) return "Low Error";
        if (relativeError <= 30) return "Moderate Error";
        if (relativeError >= 50) return "High Error";
        else return "Very High Error";
    }
    
    private String interpretR2(double r2) 
    {
       if (r2 >= 0.90) return "Excellent";
       else if (r2 >= 0.70) return "Mahusay";
       else if (r2 >= 0.50) return "Katamtaman";
       else if (r2 >= 0.25) return "Mahina";
        else return "Skill Issue";
    }
    
    private String interpretCorrelation(double correlation) 
    {
        double absR = Math.abs(correlation);
        if (correlation >= 0.90) return "Excellent";
        else if (correlation >= 0.70) return "Very Good";
        else if (correlation >= 0.50) return "Moderate";
        else if (correlation >= 0.25) return "Weak";
        else return "Very Weak";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        arffView = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblrView = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        txtMAE = new javax.swing.JTextField();
        txtRMSE = new javax.swing.JTextField();
        txtR2 = new javax.swing.JTextField();
        txtCorrelation = new javax.swing.JTextField();
        lblDataSize = new javax.swing.JLabel();
        lblArffView = new javax.swing.JLabel();
        lblTblView = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnMini = new javax.swing.JButton();
        btnAnalyze = new javax.swing.JButton();
        txtPrediction = new javax.swing.JLabel();
        txtTarget = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        arffView.setBackground(new java.awt.Color(255, 204, 204));
        arffView.setColumns(20);
        arffView.setLineWrap(true);
        arffView.setRows(5);
        arffView.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        jScrollPane1.setViewportView(arffView);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 384;
        gridBagConstraints.ipady = 314;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 48, 0, 0);
        jPanel1.add(jScrollPane1, gridBagConstraints);

        tblrView.setBackground(new java.awt.Color(255, 204, 204));
        tblrView.setColumns(20);
        tblrView.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblrView.setRows(5);
        tblrView.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        jScrollPane2.setViewportView(tblrView);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 16;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 374;
        gridBagConstraints.ipady = 314;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 24, 0, 0);
        jPanel1.add(jScrollPane2, gridBagConstraints);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        txtMAE.setBackground(new java.awt.Color(255, 204, 204));
        txtMAE.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMAE.setText("MAE:");
        txtMAE.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtMAE.addActionListener(this::txtMAEActionPerformed);

        txtRMSE.setBackground(new java.awt.Color(255, 204, 204));
        txtRMSE.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtRMSE.setText("RMSE:");
        txtRMSE.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtR2.setBackground(new java.awt.Color(255, 204, 204));
        txtR2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtR2.setText("R2:");
        txtR2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtR2.addActionListener(this::txtR2ActionPerformed);

        txtCorrelation.setBackground(new java.awt.Color(255, 204, 204));
        txtCorrelation.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCorrelation.setText("Correlation Coefficient:");
        txtCorrelation.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMAE, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRMSE, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtR2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorrelation, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(txtMAE, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRMSE, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtR2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCorrelation, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.ipady = 42;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 48, 0, 0);
        jPanel1.add(jPanel3, gridBagConstraints);

        lblDataSize.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDataSize.setText("Dataset Size:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 83, 0, 0);
        jPanel1.add(lblDataSize, gridBagConstraints);

        lblArffView.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblArffView.setText("Attribute Relation File Format (ARFF):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 48, 0, 0);
        jPanel1.add(lblArffView, gridBagConstraints);

        lblTblView.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTblView.setText("Tabular View:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 24, 0, 0);
        jPanel1.add(lblTblView, gridBagConstraints);

        btnBack.setBackground(new java.awt.Color(255, 204, 204));
        btnBack.setText("◀");
        btnBack.addActionListener(this::btnBackActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 28;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 95, 0, 0);
        jPanel1.add(btnBack, gridBagConstraints);

        btnMini.setBackground(new java.awt.Color(255, 204, 204));
        btnMini.setText("➖");
        btnMini.addActionListener(this::btnMiniActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 29;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 19;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 16);
        jPanel1.add(btnMini, gridBagConstraints);

        btnAnalyze.setText("Analyze");
        btnAnalyze.addActionListener(this::btnAnalyzeActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 70;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 0, 0, 0);
        jPanel1.add(btnAnalyze, gridBagConstraints);

        txtPrediction.setBackground(new java.awt.Color(204, 204, 255));
        txtPrediction.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPrediction.setText("Predicted Value:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 153;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 48, 0, 0);
        jPanel1.add(txtPrediction, gridBagConstraints);

        txtTarget.setBackground(new java.awt.Color(255, 204, 204));
        txtTarget.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTarget.addActionListener(this::txtTargetActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 173;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 48, 0, 0);
        jPanel1.add(txtTarget, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Target Month:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 68;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 48, 0, 0);
        jPanel1.add(jLabel6, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Knowledge Analyis");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 48, 0, 0);
        jPanel1.add(jLabel7, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("R2 = Gaano kaganda nage-explain ang model sa actual data");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("MAE = Average kung gaano kalaki ang mali ng prediction");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("RMSE = Sinusukat kung gaano kalaki ang error");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Correlation Coefficient = Gaano kalakas ang relationship ng predicted at actual values");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 18;
        gridBagConstraints.ipadx = 59;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 24, 0, 0);
        jPanel1.add(jPanel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.ipadx = 764;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 48, 0, 0);
        jPanel1.add(jSeparator1, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMiniActionPerformed
        // TODO add your handling code here:
        this.setState(java.awt.Frame.ICONIFIED);
    }//GEN-LAST:event_btnMiniActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         MainMenu previousWindow = new MainMenu();
          previousWindow.setVisible(true);
          previousWindow.setLocationRelativeTo(null);
    // 2. Close or hide the current window
          this.dispose(); 
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAnalyzeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalyzeActionPerformed
        // TODO add your handling code here:
        
        try {
        Instances data = ConverterUtils.DataSource.read("dataset.arff");
            data.setClassIndex(1);
            SimpleLinearRegression model = new SimpleLinearRegression();
            model.buildClassifier(data);
            

            
            // reserve area for evaluation
            
            //evaluation
            Evaluation eval = new Evaluation(data);
            eval.evaluateModel(model, data);
            
            //Regression Metrics
            
            double mae = eval.meanAbsoluteError();
            double rmse = eval.rootMeanSquaredError();
            double correlation = eval.correlationCoefficient();
            double rSquared = correlation * correlation;
            
            double meanActual = data.attributeStats(data.classIndex()).numericStats.mean;
            
            String maeInterpretation = interpretError(mae, meanActual);
            String rmseInterpretation = interpretError(rmse, meanActual);
            String r2Interpretation = interpretR2(rSquared);
            String corrInterpretation = interpretCorrelation(correlation);
            
            txtMAE.setText("MAE: " + String.format("%.4f", mae) + " (" + maeInterpretation + ")");
            txtRMSE.setText("RMSE: " + String.format("%.4f", rmse) + " (" + rmseInterpretation + ")");
            txtR2.setText("R2: " + String.format("%.4f", rSquared) + " (" + r2Interpretation + ")");
            txtCorrelation.setText("Correlation Coefficient: " + String.format("%.4f", correlation) + " (" + corrInterpretation + ")");
            
            
            //Display evaluation metrics
            System.out.println("==== SIMPLE LINEAR REGRESSION EVALUATION ====");
            System.out.printf("MAE     : %.4f%n", mae);
            System.out.printf("RMSE    : %.4f%n", rmse);
            System.out.printf("R2      : %.4f%n", rSquared);
            System.out.printf("Correlation Coefficient     : %.4f%n", correlation);
            // evaluation
            
            double month = Double.parseDouble(txtTarget.getText());
            
            DenseInstance test = new DenseInstance(data.numAttributes());
            test.setDataset(data);
            test.setValue(0, month);
            
            double prediction = model.classifyInstance(test);
            txtPrediction.setText("Predicted Sales: " + String.format("%.2f", prediction));
        }
        catch (Exception e)
        {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnAnalyzeActionPerformed

    private void txtTargetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTargetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTargetActionPerformed

    private void txtMAEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMAEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMAEActionPerformed

    private void txtR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtR2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtR2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SecondVersion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea arffView;
    private javax.swing.JButton btnAnalyze;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnMini;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblArffView;
    private javax.swing.JLabel lblDataSize;
    private javax.swing.JLabel lblTblView;
    private javax.swing.JTextArea tblrView;
    private javax.swing.JTextField txtCorrelation;
    private javax.swing.JTextField txtMAE;
    private javax.swing.JLabel txtPrediction;
    private javax.swing.JTextField txtR2;
    private javax.swing.JTextField txtRMSE;
    private javax.swing.JTextField txtTarget;
    // End of variables declaration//GEN-END:variables
}
